"use server";

/**
 * §3.1.4 human gates on the drafted subcontract agreement: this is a BINDING LEGAL DOCUMENT headed to a
 * third party, so it gets at least the same care as the counsel-review gate on the government-facing
 * proposal (CLAUDE.md §2/§6). Two SEPARATE, explicit admin actions:
 *   1. confirmSubcontractReview — the admin reads (and may edit) the drafted text, then confirms review.
 *      This records `agreement_reviewed_by/at`, which the `contracts_esign_requires_review` DB CHECK
 *      requires before esign_status may leave NOT_STARTED (Phase A). Always stores the CONFIRMED text as a
 *      new SUBCONTRACT_DRAFT document revision (append-only — the original AI draft is never overwritten,
 *      mirrors the documents-table no-history-erasure doctrine) so the reviewed version is the artifact of
 *      record.
 *   2. startEsign — a SEPARATE, explicit action (never automatic the instant review is confirmed). This is
 *      a STUB that flips esign_status NOT_STARTED → SENT; the real e-signature vendor integration is a
 *      later phase (§7.3). No email/outbound happens here — only a status flip + audit row.
 */
import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";

import { and, contracts, documents, eq, isNotNull, isNull, withOrg } from "@hermes/db";
import { contractDocumentKey, getStorage, sha256Hex } from "@hermes/core";
import { writeAudit } from "@hermes/inngest";

import { requireAdmin } from "@/lib/auth-guard";

// Node runtime (getStorage() needs the AWS SDK) is set on the invoking page.tsx — a "use server" module may
// only export async functions (CLAUDE.md convention), so the route-segment config cannot live here.

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const MAX_DRAFT_TEXT = 100_000;

function readId(formData: FormData, key: string): string {
  const id = String(formData.get(key) ?? "");
  if (!UUID_RE.test(id)) throw new Error(`Invalid ${key}`);
  return id;
}

/**
 * Record the admin's explicit review (and any edits) of the drafted subcontract agreement. One-time gate:
 * a contract that has already been reviewed cannot be silently re-reviewed by this action (mirrors
 * linkVendorUser's isNull one-time-binding guard) — a genuine re-review after edits is a deliberate
 * follow-on, not this action.
 */
export async function confirmSubcontractReview(formData: FormData): Promise<void> {
  const session = await requireAdmin();
  const orgId = session.user.orgId;
  const userId = session.user.id;
  const contractId = readId(formData, "contractId");
  const draftText = String(formData.get("draftText") ?? "").slice(0, MAX_DRAFT_TEXT);
  if (draftText.trim().length === 0) throw new Error("Reviewed text cannot be empty");

  const reviewed = await withOrg(orgId, async (tx) => {
    // One atomic conditional UPDATE (mirrors selectQuote's single-winner guard): only an existing,
    // NOT-yet-reviewed contract in THIS org can be confirmed — no read-then-write TOCTOU window, and a
    // contract that was already reviewed (or does not exist) is simply a no-op, never a silent overwrite.
    const updated = await tx
      .update(contracts)
      .set({ agreementReviewedBy: userId, agreementReviewedAt: new Date() })
      .where(and(eq(contracts.orgId, orgId), eq(contracts.id, contractId), isNull(contracts.agreementReviewedBy)))
      .returning({ id: contracts.id, solicitationId: contracts.solicitationId });
    const contract = updated[0];
    if (!contract) return null; // not found, or already reviewed — no-op

    // Store the CONFIRMED text as a new, append-only SUBCONTRACT_DRAFT revision (the AI-drafted original
    // is never overwritten — mirrors the documents table's no-history-erasure doctrine).
    const documentId = randomUUID();
    const bytes = new TextEncoder().encode(draftText);
    const key = contractDocumentKey(orgId, contractId, documentId, "md");
    await getStorage().put(key, bytes, "text/markdown");
    await tx.insert(documents).values({
      id: documentId,
      orgId,
      entityType: "CONTRACT",
      contractId,
      kind: "SUBCONTRACT_DRAFT",
      storageKey: key,
      contentType: "text/markdown",
      byteSize: bytes.byteLength,
      sha256: sha256Hex(bytes),
      magicByteValidated: true, // system-generated bytes, not a client upload
    });

    await writeAudit(tx, {
      orgId,
      actorType: "ADMIN",
      actorUserId: userId,
      actorEmail: session.user.email ?? null,
      action: "CONTRACT_AGREEMENT_REVIEWED",
      entityType: "contracts",
      entityId: contractId,
      after: { documentId },
    });
    return contract.solicitationId;
  });

  if (reviewed) {
    revalidatePath(`/admin/solicitations/${reviewed}/subcontract`);
  }
}

/**
 * STUB: flip esign_status NOT_STARTED → SENT. This is a SEPARATE, explicit admin action from review — it
 * never fires automatically the instant confirmSubcontractReview runs. No vendor is contacted here; the
 * real e-signature vendor integration (send/track/webhook) is a later phase (§7.3). The DB CHECK
 * (contracts_esign_requires_review) is the structural backstop: this can only ever succeed once a review
 * is recorded, but the WHERE clause guards it too so an un-reviewed contract simply no-ops.
 */
export async function startEsign(formData: FormData): Promise<void> {
  const session = await requireAdmin();
  const orgId = session.user.orgId;
  const userId = session.user.id;
  const contractId = readId(formData, "contractId");

  const started = await withOrg(orgId, async (tx) => {
    const rows = await tx
      .update(contracts)
      .set({ esignStatus: "SENT" })
      .where(
        and(
          eq(contracts.orgId, orgId),
          eq(contracts.id, contractId),
          eq(contracts.esignStatus, "NOT_STARTED"),
          isNotNull(contracts.agreementReviewedBy), // app-layer guard mirroring the DB CHECK
        ),
      )
      .returning({ id: contracts.id, solicitationId: contracts.solicitationId });
    const row = rows[0];
    if (!row) return null;

    await writeAudit(tx, {
      orgId,
      actorType: "ADMIN",
      actorUserId: userId,
      actorEmail: session.user.email ?? null,
      action: "CONTRACT_ESIGN_STARTED",
      entityType: "contracts",
      entityId: contractId,
    });
    return row.solicitationId;
  });

  if (started) {
    revalidatePath(`/admin/solicitations/${started}/subcontract`);
  }
}
