/**
 * The schema CONTRACT, transcribed from migrations/0000_tables.sql. The contract test asserts the
 * live database matches this exactly (set-equality), so an accidental column/type/nullability/enum
 * drift fails CI. `udt` is the Postgres `information_schema.columns.udt_name` (e.g. uuid, text,
 * varchar, jsonb, timestamptz, int4, bool, numeric, vector, or the enum type name).
 */
export interface ColumnSpec {
  name: string;
  udt: string;
  nullable: boolean;
}

const ts = (name: string, nullable = true): ColumnSpec => ({ name, udt: "timestamptz", nullable });
const stamps: ColumnSpec[] = [ts("created_at", false), ts("updated_at", false)];

export const EXPECTED_COLUMNS: Record<string, ColumnSpec[]> = {
  orgs: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "slug", udt: "text", nullable: false },
    { name: "name", udt: "text", nullable: false },
    { name: "ein", udt: "varchar", nullable: true },
    { name: "uei", udt: "varchar", nullable: true },
    { name: "cage_code", udt: "varchar", nullable: true },
    { name: "primary_domain", udt: "text", nullable: true },
    { name: "directives", udt: "jsonb", nullable: false },
    ...stamps,
  ],
  users: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "email", udt: "text", nullable: false },
    { name: "password_hash", udt: "text", nullable: true },
    { name: "role", udt: "user_role", nullable: false },
    { name: "admin_role", udt: "admin_role", nullable: true },
    { name: "vendor_id", udt: "uuid", nullable: true },
    { name: "totp_secret_ciphertext", udt: "text", nullable: true },
    { name: "totp_enrolled_at", udt: "timestamptz", nullable: true },
    { name: "failed_login_count", udt: "int4", nullable: false },
    { name: "locked_until", udt: "timestamptz", nullable: true },
    { name: "is_active", udt: "bool", nullable: false },
    ...stamps,
  ],
  audit_log: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "actor_user_id", udt: "uuid", nullable: true },
    { name: "actor_type", udt: "actor_type", nullable: false },
    { name: "actor_email", udt: "text", nullable: true },
    { name: "action", udt: "text", nullable: false },
    { name: "entity_type", udt: "text", nullable: true },
    { name: "entity_id", udt: "uuid", nullable: true },
    { name: "before", udt: "jsonb", nullable: true },
    { name: "after", udt: "jsonb", nullable: true },
    { name: "ip", udt: "text", nullable: true },
    ts("created_at", false), // append-only: no updated_at
  ],
  contact_inquiries: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "name", udt: "text", nullable: false },
    { name: "email", udt: "text", nullable: false },
    { name: "company", udt: "text", nullable: true },
    { name: "intent", udt: "inquiry_intent", nullable: false },
    { name: "message", udt: "text", nullable: false },
    { name: "status", udt: "inquiry_status", nullable: false },
    ...stamps,
  ],
  award_intelligence: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "piid", udt: "text", nullable: true },
    { name: "award_unique_key", udt: "text", nullable: false },
    { name: "naics_code", udt: "varchar", nullable: true },
    { name: "agency", udt: "text", nullable: true },
    { name: "recipient", udt: "text", nullable: true },
    { name: "award_amount", udt: "numeric", nullable: true },
    { name: "award_amount_kind", udt: "award_amount_kind", nullable: false },
    { name: "raw", udt: "jsonb", nullable: true },
    ts("fetched_at", false),
    ...stamps,
  ],
  solicitations: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "notice_id", udt: "text", nullable: false },
    { name: "title", udt: "text", nullable: false },
    { name: "agency", udt: "text", nullable: true },
    { name: "naics_code", udt: "varchar", nullable: true },
    { name: "psc_code", udt: "varchar", nullable: true },
    { name: "notice_type", udt: "notice_type", nullable: true },
    { name: "set_aside_type", udt: "set_aside_type", nullable: false },
    { name: "contract_type", udt: "contract_type", nullable: true },
    { name: "is_services", udt: "bool", nullable: true },
    { name: "is_services_source", udt: "classification_source", nullable: true },
    { name: "is_defense", udt: "bool", nullable: false },
    { name: "response_deadline", udt: "timestamptz", nullable: true },
    { name: "scope_text", udt: "text", nullable: true },
    { name: "scope_embedding", udt: "vector", nullable: true },
    { name: "quote_injection_attempts", udt: "jsonb", nullable: true },
    { name: "status", udt: "solicitation_status", nullable: false },
    { name: "feasibility_score", udt: "int4", nullable: true },
    { name: "zero_float_fit", udt: "zero_float_fit", nullable: true },
    { name: "rejection_reasons", udt: "jsonb", nullable: true },
    { name: "triage_model", udt: "text", nullable: true },
    { name: "triage_summary", udt: "text", nullable: true },
    { name: "triage_recommendation", udt: "ai_recommendation", nullable: true },
    { name: "triaged_at", udt: "timestamptz", nullable: true },
    { name: "sourcing_approved_by", udt: "uuid", nullable: true },
    { name: "sourcing_approved_at", udt: "timestamptz", nullable: true },
    // Phase A: deal role + award-outcome block + RFI track + L/M matrix (§3.1/§3.4/§3.8).
    { name: "deal_role", udt: "deal_role", nullable: false },
    { name: "awarded_piid", udt: "text", nullable: true },
    { name: "awarded_value", udt: "numeric", nullable: true },
    { name: "award_date", udt: "timestamptz", nullable: true },
    { name: "co_contact", udt: "jsonb", nullable: true },
    { name: "debrief_requested", udt: "bool", nullable: false },
    { name: "debrief_notes", udt: "text", nullable: true },
    { name: "protest_status", udt: "protest_status", nullable: false },
    { name: "protest_notes", udt: "text", nullable: true },
    { name: "outcome_notes", udt: "text", nullable: true },
    { name: "outcome_recorded_by", udt: "uuid", nullable: true },
    { name: "outcome_recorded_at", udt: "timestamptz", nullable: true },
    { name: "rfi_track_status", udt: "rfi_track_status", nullable: true },
    { name: "converted_from_solicitation_id", udt: "uuid", nullable: true },
    { name: "lm_compliance_matrix", udt: "jsonb", nullable: true },
    { name: "lm_extracted_at", udt: "timestamptz", nullable: true },
    { name: "lm_extraction_model", udt: "text", nullable: true },
    ...stamps,
  ],
  outreach_campaigns: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "solicitation_id", udt: "uuid", nullable: false },
    { name: "prospect_id", udt: "uuid", nullable: false },
    { name: "step", udt: "outreach_step", nullable: false },
    { name: "status", udt: "outreach_status", nullable: false },
    { name: "subject", udt: "text", nullable: false },
    { name: "body", udt: "text", nullable: false },
    { name: "ai_match_score", udt: "int4", nullable: true },
    { name: "ai_capability_match", udt: "numeric", nullable: true },
    { name: "ai_strengths", udt: "jsonb", nullable: true },
    { name: "ai_gaps", udt: "jsonb", nullable: true },
    { name: "ai_recommendation", udt: "ai_recommendation", nullable: true },
    { name: "quote_token_hash", udt: "text", nullable: true },
    { name: "quote_token_expires_at", udt: "timestamptz", nullable: true },
    { name: "optout_token_hash", udt: "text", nullable: true },
    { name: "optout_token_expires_at", udt: "timestamptz", nullable: true },
    { name: "approved_by", udt: "uuid", nullable: true },
    { name: "approved_at", udt: "timestamptz", nullable: true },
    { name: "sent_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  vendor_prospects: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "company_name", udt: "text", nullable: false },
    { name: "contact_email", udt: "text", nullable: true },
    { name: "uei", udt: "varchar", nullable: true },
    { name: "naics_codes", udt: "jsonb", nullable: false },
    { name: "capabilities_text", udt: "text", nullable: true },
    { name: "capability_embedding", udt: "vector", nullable: true },
    { name: "discovery_score", udt: "int4", nullable: true },
    { name: "discovery_metadata", udt: "jsonb", nullable: true },
    { name: "prospect_source", udt: "prospect_source", nullable: false },
    { name: "status", udt: "prospect_status", nullable: false },
    ...stamps,
  ],
  vendors: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "promoted_from_prospect_id", udt: "uuid", nullable: true },
    { name: "company_name", udt: "text", nullable: false },
    { name: "contact_email", udt: "text", nullable: true },
    { name: "uei", udt: "varchar", nullable: true },
    { name: "cage_code", udt: "varchar", nullable: true },
    { name: "small_business_status", udt: "small_business_status", nullable: false },
    { name: "similarly_situated", udt: "bool", nullable: true },
    { name: "small_under_naics", udt: "jsonb", nullable: false },
    { name: "capabilities_text", udt: "text", nullable: true },
    { name: "capability_embedding", udt: "vector", nullable: true },
    { name: "status", udt: "vendor_status", nullable: false },
    { name: "vetted_by", udt: "uuid", nullable: true },
    { name: "vetted_at", udt: "timestamptz", nullable: true },
    { name: "insurance_expiry", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  vendor_invites: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "vendor_id", udt: "uuid", nullable: false },
    { name: "invited_email", udt: "text", nullable: false },
    { name: "token_hash", udt: "text", nullable: false },
    { name: "token_jti", udt: "text", nullable: false },
    { name: "expires_at", udt: "timestamptz", nullable: false },
    { name: "accepted_at", udt: "timestamptz", nullable: true },
    { name: "accepted_user_id", udt: "uuid", nullable: true },
    { name: "created_by", udt: "uuid", nullable: false },
    ...stamps,
  ],
  proposals: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "solicitation_id", udt: "uuid", nullable: false },
    { name: "selected_quote_id", udt: "uuid", nullable: true },
    { name: "awarded_vendor_id", udt: "uuid", nullable: true },
    { name: "supersedes_proposal_id", udt: "uuid", nullable: true },
    { name: "contract_type", udt: "contract_type", nullable: false },
    { name: "status", udt: "proposal_status", nullable: false },
    { name: "pricing_scenarios", udt: "jsonb", nullable: true },
    { name: "compliance_checklist", udt: "jsonb", nullable: true },
    { name: "narrative", udt: "jsonb", nullable: true },
    { name: "prime_qualifying_status", udt: "small_business_status", nullable: true },
    { name: "prime_qualifying_naics", udt: "varchar", nullable: true },
    { name: "government_payment_basis", udt: "numeric", nullable: true },
    { name: "non_similarly_situated_subs_total", udt: "numeric", nullable: true },
    { name: "total_cost_of_work", udt: "numeric", nullable: true },
    { name: "adequate_price_competition", udt: "bool", nullable: true },
    { name: "pass_through_justification", udt: "text", nullable: true },
    { name: "submitted_by", udt: "uuid", nullable: true },
    { name: "submitted_at", udt: "timestamptz", nullable: true },
    { name: "counsel_reviewed_by", udt: "uuid", nullable: true },
    { name: "counsel_reviewed_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  vendor_quote_line_items: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "quote_id", udt: "uuid", nullable: false },
    { name: "cost_type", udt: "cost_type", nullable: false },
    { name: "contract_type", udt: "contract_type", nullable: false },
    { name: "description", udt: "text", nullable: false },
    { name: "quantity", udt: "numeric", nullable: false },
    { name: "unit_rate", udt: "numeric", nullable: false },
    { name: "markup_pct", udt: "numeric", nullable: false },
    { name: "extended_amount", udt: "numeric", nullable: true },
    { name: "similarly_situated", udt: "bool", nullable: true },
    { name: "sub_small_business_status", udt: "small_business_status", nullable: true },
    { name: "sub_subcontract_naics", udt: "varchar", nullable: true },
    ...stamps,
  ],
  vendor_quotes: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "solicitation_id", udt: "uuid", nullable: false },
    { name: "vendor_id", udt: "uuid", nullable: true },
    { name: "prospect_id", udt: "uuid", nullable: true },
    { name: "token_jti", udt: "text", nullable: true },
    { name: "status", udt: "quote_status", nullable: false },
    { name: "total_price", udt: "numeric", nullable: true },
    { name: "period_of_performance", udt: "text", nullable: true },
    { name: "pay_when_paid", udt: "bool", nullable: false },
    { name: "notes", udt: "text", nullable: true },
    { name: "ai_rank", udt: "int4", nullable: true },
    { name: "ai_rationale", udt: "text", nullable: true },
    { name: "ai_score", udt: "numeric", nullable: true },
    { name: "ai_risks", udt: "jsonb", nullable: true },
    { name: "evaluated_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  ar_followups: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "contract_id", udt: "uuid", nullable: false },
    { name: "milestone_id", udt: "uuid", nullable: true },
    { name: "amount_due", udt: "numeric", nullable: true },
    { name: "due_date", udt: "timestamptz", nullable: true },
    { name: "status", udt: "ar_followup_status", nullable: false },
    { name: "next_followup_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  contract_milestones: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "contract_id", udt: "uuid", nullable: false },
    { name: "sequence", udt: "int4", nullable: false },
    { name: "description", udt: "text", nullable: false },
    { name: "amount", udt: "numeric", nullable: true },
    { name: "due_date", udt: "timestamptz", nullable: true },
    { name: "status", udt: "milestone_status", nullable: false },
    ...stamps,
  ],
  contracts: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "solicitation_id", udt: "uuid", nullable: true },
    { name: "proposal_id", udt: "uuid", nullable: true },
    { name: "awarded_vendor_id", udt: "uuid", nullable: true },
    { name: "contract_type", udt: "contract_type", nullable: false },
    { name: "total_value", udt: "numeric", nullable: true },
    { name: "pop_start", udt: "timestamptz", nullable: true },
    { name: "pop_end", udt: "timestamptz", nullable: true },
    { name: "status", udt: "contract_status", nullable: false },
    { name: "esign_status", udt: "esign_status", nullable: false },
    // Phase A: §3.1.4 agreement-review gate + §3.3 accelerated payments + §7.3 signer substrate.
    { name: "agreement_reviewed_by", udt: "uuid", nullable: true },
    { name: "agreement_reviewed_at", udt: "timestamptz", nullable: true },
    { name: "accelerated_payments", udt: "bool", nullable: false },
    { name: "vendor_signed_by_user_id", udt: "uuid", nullable: true },
    { name: "vendor_signed_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  documents: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "entity_type", udt: "document_entity_type", nullable: false },
    { name: "solicitation_id", udt: "uuid", nullable: true },
    { name: "vendor_id", udt: "uuid", nullable: true },
    { name: "prospect_id", udt: "uuid", nullable: true },
    { name: "quote_id", udt: "uuid", nullable: true },
    { name: "proposal_id", udt: "uuid", nullable: true },
    { name: "contract_id", udt: "uuid", nullable: true },
    { name: "milestone_id", udt: "uuid", nullable: true },
    // Phase A (O3): the two new owners + the §3.7.3 retention fields.
    { name: "teaming_agreement_id", udt: "uuid", nullable: true },
    { name: "insurance_policy_id", udt: "uuid", nullable: true },
    { name: "kind", udt: "document_kind", nullable: false },
    { name: "storage_key", udt: "text", nullable: false },
    { name: "content_type", udt: "text", nullable: false },
    { name: "byte_size", udt: "int4", nullable: false },
    { name: "sha256", udt: "varchar", nullable: true },
    { name: "magic_byte_validated", udt: "bool", nullable: false },
    { name: "retention_until", udt: "timestamptz", nullable: true },
    { name: "retention_reviewed_by", udt: "uuid", nullable: true },
    { name: "retention_reviewed_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  // ---- Phase A (§3.4): reverse-subcontracting cluster ----
  teaming_partners: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "company_name", udt: "text", nullable: false },
    { name: "contact_name", udt: "text", nullable: true },
    { name: "contact_email", udt: "text", nullable: true },
    { name: "contact_phone", udt: "text", nullable: true },
    { name: "uei", udt: "varchar", nullable: true },
    { name: "cage_code", udt: "varchar", nullable: true },
    { name: "notes", udt: "text", nullable: true },
    ...stamps,
  ],
  teaming_agreements: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "partner_id", udt: "uuid", nullable: false },
    { name: "solicitation_id", udt: "uuid", nullable: true },
    { name: "our_scope_text", udt: "text", nullable: true },
    { name: "our_pricing", udt: "numeric", nullable: true },
    { name: "pop_start", udt: "timestamptz", nullable: true },
    { name: "pop_end", udt: "timestamptz", nullable: true },
    { name: "prime_contract_piid", udt: "text", nullable: true },
    { name: "status", udt: "teaming_agreement_status", nullable: false },
    ...stamps,
  ],
  // ---- Phase A (§3.3): finance cluster ----
  invoices: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "contract_id", udt: "uuid", nullable: true },
    { name: "teaming_agreement_id", udt: "uuid", nullable: true },
    { name: "milestone_id", udt: "uuid", nullable: true },
    { name: "invoice_number", udt: "text", nullable: false },
    { name: "kind", udt: "invoice_kind", nullable: false },
    { name: "amount", udt: "numeric", nullable: false },
    { name: "submitted_at", udt: "timestamptz", nullable: true },
    { name: "paid_at", udt: "timestamptz", nullable: true },
    { name: "status", udt: "invoice_status", nullable: false },
    { name: "notes", udt: "text", nullable: true },
    ...stamps,
  ],
  subcontractor_payables: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "contract_id", udt: "uuid", nullable: false },
    { name: "milestone_id", udt: "uuid", nullable: true },
    { name: "amount", udt: "numeric", nullable: false },
    { name: "government_invoice_id", udt: "uuid", nullable: true },
    { name: "paid_at", udt: "timestamptz", nullable: true },
    { name: "status", udt: "payable_status", nullable: false },
    ...stamps,
  ],
  past_performance_records: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "contract_id", udt: "uuid", nullable: false },
    { name: "rating_period_start", udt: "timestamptz", nullable: true },
    { name: "rating_period_end", udt: "timestamptz", nullable: true },
    { name: "rating", udt: "cpars_rating", nullable: false },
    { name: "narrative", udt: "text", nullable: true },
    { name: "evaluator_name", udt: "text", nullable: true },
    { name: "evaluator_email", udt: "text", nullable: true },
    { name: "recorded_by", udt: "uuid", nullable: false },
    ts("recorded_at", false),
    ...stamps,
  ],
  ai_usage_events: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    ts("occurred_at", false),
    { name: "model", udt: "text", nullable: false },
    { name: "function_name", udt: "text", nullable: false },
    { name: "input_tokens", udt: "int4", nullable: false },
    { name: "output_tokens", udt: "int4", nullable: false },
    { name: "cache_read_tokens", udt: "int4", nullable: false },
    { name: "cache_write_tokens", udt: "int4", nullable: false },
    { name: "estimated_cost_usd", udt: "numeric", nullable: true },
    ...stamps,
  ],
  // ---- Phase A (§3.5): DCAA timekeeping cluster ----
  timesheet_periods: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "user_id", udt: "uuid", nullable: false },
    { name: "period_start", udt: "date", nullable: false },
    { name: "period_end", udt: "date", nullable: false },
    { name: "status", udt: "timesheet_status", nullable: false },
    { name: "submitted_at", udt: "timestamptz", nullable: true },
    { name: "approved_by", udt: "uuid", nullable: true },
    { name: "approved_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  time_entries: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "user_id", udt: "uuid", nullable: false },
    { name: "work_date", udt: "date", nullable: false },
    { name: "hours", udt: "numeric", nullable: false },
    { name: "charge_class", udt: "time_charge_class", nullable: false },
    { name: "contract_id", udt: "uuid", nullable: true },
    { name: "milestone_id", udt: "uuid", nullable: true },
    { name: "description", udt: "text", nullable: false },
    { name: "period_id", udt: "uuid", nullable: true },
    { name: "invoice_id", udt: "uuid", nullable: true },
    ...stamps,
  ],
  time_entry_corrections: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "time_entry_id", udt: "uuid", nullable: false },
    { name: "corrected_by", udt: "uuid", nullable: false },
    ts("corrected_at", false), // append-only: no created_at/updated_at (corrected_at IS the stamp)
    { name: "old_values", udt: "jsonb", nullable: false },
    { name: "new_values", udt: "jsonb", nullable: false },
    { name: "reason", udt: "text", nullable: false },
  ],
  // ---- Phase A (§3.7): firm-side compliance cluster ----
  business_insurance_policies: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "policy_type", udt: "insurance_policy_type", nullable: false },
    { name: "carrier", udt: "text", nullable: true },
    { name: "policy_number", udt: "text", nullable: true },
    { name: "coverage_amount", udt: "numeric", nullable: true },
    { name: "effective_at", udt: "timestamptz", nullable: true },
    { name: "expires_at", udt: "timestamptz", nullable: true },
    { name: "notes", udt: "text", nullable: true },
    ...stamps,
  ],
  compliance_events: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "kind", udt: "compliance_event_kind", nullable: false },
    ts("occurred_at", false),
    { name: "notes", udt: "text", nullable: true },
    { name: "recorded_by", udt: "uuid", nullable: false },
    ...stamps,
  ],
};

export const EXPECTED_TABLES: string[] = Object.keys(EXPECTED_COLUMNS);

/** All 41 enums and their labels, in sort order. */
export const EXPECTED_ENUMS: Record<string, string[]> = {
  actor_type: ["SYSTEM", "ADMIN", "VENDOR", "TOKEN"],
  admin_role: ["FULL", "CAPTURE", "FINANCE"],
  ai_recommendation: ["PURSUE", "REJECT", "HUMAN_REVIEW"],
  ar_followup_status: ["SCHEDULED", "SENT", "PAID", "ESCALATED", "WRITTEN_OFF"],
  award_amount_kind: ["EXACT", "ESTIMATED", "CEILING", "OBLIGATED", "UNKNOWN"],
  classification_source: ["AI_TRIAGE", "HUMAN", "SAM_GOV", "HEURISTIC"],
  compliance_event_kind: ["OPTION_YEAR_RECERT", "SIZE_RECERT", "MERGER_ACQUISITION", "OTHER"],
  contract_status: ["PENDING_SIGNATURE", "ACTIVE", "COMPLETED", "TERMINATED", "CLOSED_OUT"],
  contract_type: ["FFP", "TM", "FFP_MILESTONE"],
  cost_type: ["LABOR", "MATERIAL", "ODC", "SUBCONTRACT", "TRAVEL"],
  cpars_rating: ["EXCEPTIONAL", "VERY_GOOD", "SATISFACTORY", "MARGINAL", "UNSATISFACTORY"],
  deal_role: ["PRIME", "SUBCONTRACTOR"],
  document_entity_type: [
    "SOLICITATION",
    "VENDOR",
    "VENDOR_PROSPECT",
    "VENDOR_QUOTE",
    "PROPOSAL",
    "CONTRACT",
    "CONTRACT_MILESTONE",
    "TEAMING_AGREEMENT",
    "INSURANCE_POLICY",
  ],
  document_kind: [
    "SOLICITATION_ATTACHMENT",
    "CAPABILITY_STATEMENT",
    "COI",
    "W9",
    "QUOTE",
    "PROPOSAL_DRAFT",
    "PROPOSAL_FINAL",
    "SIGNED_CONTRACT",
    "DELIVERABLE",
    "OTHER",
    "SUBCONTRACT_DRAFT",
  ],
  esign_status: ["NOT_STARTED", "SENT", "SIGNED", "DECLINED", "EXPIRED"],
  insurance_policy_type: ["GENERAL_LIABILITY", "PROFESSIONAL_EO", "CYBER", "BOND", "OTHER"],
  invoice_kind: ["PROGRESS", "FINAL"],
  invoice_status: ["DRAFT", "SUBMITTED", "PAID", "CANCELLED"],
  inquiry_intent: ["TEAMING", "AGENCY", "OTHER"],
  inquiry_status: ["NEW", "REVIEWED"],
  milestone_status: ["PENDING", "IN_PROGRESS", "COMPLETED", "INVOICED", "PAID"],
  notice_type: [
    "SOLICITATION",
    "COMBINED_SYNOPSIS_SOLICITATION",
    "PRESOLICITATION",
    "SOURCES_SOUGHT",
    "RFI",
    "SPECIAL_NOTICE",
    "AWARD_NOTICE",
    "JUSTIFICATION",
  ],
  outreach_status: [
    "DRAFT",
    "PENDING_APPROVAL",
    "APPROVED",
    "SENT",
    "BOUNCED",
    "RESPONDED",
    "OPTED_OUT",
    "CANCELLED",
  ],
  outreach_step: ["DAY_0", "DAY_3", "DAY_7"],
  payable_status: ["PENDING", "PAID"],
  proposal_status: [
    "DRAFT",
    "PRICING_REVIEW",
    "COMPLIANCE_REVIEW",
    "COUNSEL_REVIEW",
    "READY_TO_SUBMIT",
    "SUBMITTED",
    "WON",
    "LOST",
    "WITHDRAWN",
  ],
  prospect_source: ["DISCOVERY", "TOKENIZED_SUBMISSION", "MANUAL", "REFERRAL"],
  protest_status: [
    "NONE",
    "CONSIDERING",
    "FILED",
    "RESOLVED_SUSTAINED",
    "RESOLVED_DENIED",
    "WITHDRAWN",
  ],
  prospect_status: [
    "NEW",
    "SCREENED",
    "CONTACTED",
    "RESPONDED",
    "QUALIFIED",
    "PROMOTED",
    "DECLINED",
    "OPTED_OUT",
  ],
  quote_status: [
    "INVITED",
    "DRAFT",
    "SUBMITTED",
    "UNDER_REVIEW",
    "SHORTLISTED",
    "REJECTED",
    "WITHDRAWN",
    "SELECTED",
  ],
  rfi_track_status: [
    "RECEIVED",
    "CAPABILITY_DRAFTED",
    "RESPONSE_SUBMITTED",
    "CONVERTED",
    "CLOSED_NO_ACTION",
  ],
  set_aside_type: ["NONE", "TOTAL_SMALL_BUSINESS", "EIGHT_A", "HUBZONE", "SDVOSB", "WOSB", "OTHER"],
  small_business_status: ["SMALL", "OTHER_THAN_SMALL", "UNKNOWN"],
  solicitation_status: [
    "PENDING_TRIAGE",
    "TRIAGE_COMPLETE",
    "NO_GO",
    "READY_FOR_SOURCING",
    "AWAITING_APPROVAL",
    "SOURCING_IN_PROGRESS",
    "PRICING_PENDING",
    "PROPOSAL_DRAFT",
    "SUBMITTED",
    "AWARDED",
    "CLOSED",
    "REJECTED",
  ],
  teaming_agreement_status: ["DRAFT", "UNDER_NEGOTIATION", "EXECUTED", "TERMINATED", "CLOSED"],
  time_charge_class: ["DIRECT", "INDIRECT"],
  timesheet_status: ["OPEN", "SUBMITTED", "APPROVED"],
  token_purpose: ["QUOTE_SUBMISSION", "OPT_OUT", "VENDOR_INVITE"],
  user_role: ["ADMIN", "VENDOR"],
  vendor_status: ["PENDING_REVIEW", "VETTED", "NON_COMPLIANT", "EXCLUDED"],
  zero_float_fit: ["STRONG", "MODERATE", "WEAK", "NONE"],
};
