/**
 * The schema CONTRACT, transcribed from migrations/0000_tables.sql. The contract test asserts the
 * live database matches this exactly (set-equality), so an accidental column/type/nullability/enum
 * drift fails CI. `udt` is the Postgres `information_schema.columns.udt_name` (e.g. uuid, text,
 * varchar, jsonb, timestamptz, int4, bool, numeric, vector, or the enum type name).
 */
export interface ColumnSpec {
  name: string;
  udt: string;
  nullable: boolean;
}

const ts = (name: string, nullable = true): ColumnSpec => ({ name, udt: "timestamptz", nullable });
const stamps: ColumnSpec[] = [ts("created_at", false), ts("updated_at", false)];

export const EXPECTED_COLUMNS: Record<string, ColumnSpec[]> = {
  orgs: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "slug", udt: "text", nullable: false },
    { name: "name", udt: "text", nullable: false },
    { name: "ein", udt: "varchar", nullable: true },
    { name: "uei", udt: "varchar", nullable: true },
    { name: "cage_code", udt: "varchar", nullable: true },
    { name: "primary_domain", udt: "text", nullable: true },
    { name: "directives", udt: "jsonb", nullable: false },
    ...stamps,
  ],
  users: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "email", udt: "text", nullable: false },
    { name: "password_hash", udt: "text", nullable: true },
    { name: "role", udt: "user_role", nullable: false },
    { name: "totp_secret_ciphertext", udt: "text", nullable: true },
    { name: "totp_enrolled_at", udt: "timestamptz", nullable: true },
    { name: "failed_login_count", udt: "int4", nullable: false },
    { name: "locked_until", udt: "timestamptz", nullable: true },
    { name: "is_active", udt: "bool", nullable: false },
    ...stamps,
  ],
  audit_log: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "actor_user_id", udt: "uuid", nullable: true },
    { name: "actor_type", udt: "actor_type", nullable: false },
    { name: "actor_email", udt: "text", nullable: true },
    { name: "action", udt: "text", nullable: false },
    { name: "entity_type", udt: "text", nullable: true },
    { name: "entity_id", udt: "uuid", nullable: true },
    { name: "before", udt: "jsonb", nullable: true },
    { name: "after", udt: "jsonb", nullable: true },
    { name: "ip", udt: "text", nullable: true },
    ts("created_at", false), // append-only: no updated_at
  ],
  award_intelligence: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "piid", udt: "text", nullable: true },
    { name: "award_unique_key", udt: "text", nullable: false },
    { name: "naics_code", udt: "varchar", nullable: true },
    { name: "agency", udt: "text", nullable: true },
    { name: "recipient", udt: "text", nullable: true },
    { name: "award_amount", udt: "numeric", nullable: true },
    { name: "award_amount_kind", udt: "award_amount_kind", nullable: false },
    { name: "raw", udt: "jsonb", nullable: true },
    ts("fetched_at", false),
    ...stamps,
  ],
  solicitations: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "notice_id", udt: "text", nullable: false },
    { name: "title", udt: "text", nullable: false },
    { name: "agency", udt: "text", nullable: true },
    { name: "naics_code", udt: "varchar", nullable: true },
    { name: "psc_code", udt: "varchar", nullable: true },
    { name: "notice_type", udt: "notice_type", nullable: true },
    { name: "set_aside_type", udt: "set_aside_type", nullable: false },
    { name: "contract_type", udt: "contract_type", nullable: true },
    { name: "is_services", udt: "bool", nullable: true },
    { name: "is_services_source", udt: "classification_source", nullable: true },
    { name: "is_defense", udt: "bool", nullable: false },
    { name: "response_deadline", udt: "timestamptz", nullable: true },
    { name: "scope_text", udt: "text", nullable: true },
    { name: "scope_embedding", udt: "vector", nullable: true },
    { name: "status", udt: "solicitation_status", nullable: false },
    { name: "feasibility_score", udt: "int4", nullable: true },
    { name: "zero_float_fit", udt: "zero_float_fit", nullable: true },
    { name: "rejection_reasons", udt: "jsonb", nullable: true },
    { name: "triage_model", udt: "text", nullable: true },
    { name: "triaged_at", udt: "timestamptz", nullable: true },
    { name: "sourcing_approved_by", udt: "uuid", nullable: true },
    { name: "sourcing_approved_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  outreach_campaigns: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "solicitation_id", udt: "uuid", nullable: false },
    { name: "prospect_id", udt: "uuid", nullable: false },
    { name: "step", udt: "outreach_step", nullable: false },
    { name: "status", udt: "outreach_status", nullable: false },
    { name: "subject", udt: "text", nullable: false },
    { name: "body", udt: "text", nullable: false },
    { name: "quote_token_hash", udt: "text", nullable: true },
    { name: "quote_token_expires_at", udt: "timestamptz", nullable: true },
    { name: "optout_token_hash", udt: "text", nullable: true },
    { name: "optout_token_expires_at", udt: "timestamptz", nullable: true },
    { name: "approved_by", udt: "uuid", nullable: true },
    { name: "approved_at", udt: "timestamptz", nullable: true },
    { name: "sent_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  vendor_prospects: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "company_name", udt: "text", nullable: false },
    { name: "contact_email", udt: "text", nullable: true },
    { name: "uei", udt: "varchar", nullable: true },
    { name: "naics_codes", udt: "jsonb", nullable: false },
    { name: "capabilities_text", udt: "text", nullable: true },
    { name: "capability_embedding", udt: "vector", nullable: true },
    { name: "discovery_score", udt: "int4", nullable: true },
    { name: "prospect_source", udt: "prospect_source", nullable: false },
    { name: "status", udt: "prospect_status", nullable: false },
    ...stamps,
  ],
  vendors: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "promoted_from_prospect_id", udt: "uuid", nullable: true },
    { name: "company_name", udt: "text", nullable: false },
    { name: "contact_email", udt: "text", nullable: true },
    { name: "uei", udt: "varchar", nullable: true },
    { name: "cage_code", udt: "varchar", nullable: true },
    { name: "small_business_status", udt: "small_business_status", nullable: false },
    { name: "similarly_situated", udt: "bool", nullable: true },
    { name: "small_under_naics", udt: "jsonb", nullable: false },
    { name: "capabilities_text", udt: "text", nullable: true },
    { name: "capability_embedding", udt: "vector", nullable: true },
    { name: "status", udt: "vendor_status", nullable: false },
    { name: "vetted_by", udt: "uuid", nullable: true },
    { name: "vetted_at", udt: "timestamptz", nullable: true },
    { name: "insurance_expiry", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  proposals: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "solicitation_id", udt: "uuid", nullable: false },
    { name: "selected_quote_id", udt: "uuid", nullable: true },
    { name: "awarded_vendor_id", udt: "uuid", nullable: true },
    { name: "supersedes_proposal_id", udt: "uuid", nullable: true },
    { name: "contract_type", udt: "contract_type", nullable: false },
    { name: "status", udt: "proposal_status", nullable: false },
    { name: "pricing_scenarios", udt: "jsonb", nullable: true },
    { name: "compliance_checklist", udt: "jsonb", nullable: true },
    { name: "prime_qualifying_status", udt: "small_business_status", nullable: true },
    { name: "prime_qualifying_naics", udt: "varchar", nullable: true },
    { name: "government_payment_basis", udt: "numeric", nullable: true },
    { name: "non_similarly_situated_subs_total", udt: "numeric", nullable: true },
    { name: "total_cost_of_work", udt: "numeric", nullable: true },
    { name: "adequate_price_competition", udt: "bool", nullable: true },
    { name: "pass_through_justification", udt: "text", nullable: true },
    { name: "submitted_by", udt: "uuid", nullable: true },
    { name: "submitted_at", udt: "timestamptz", nullable: true },
    { name: "counsel_reviewed_by", udt: "uuid", nullable: true },
    { name: "counsel_reviewed_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  vendor_quote_line_items: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "quote_id", udt: "uuid", nullable: false },
    { name: "cost_type", udt: "cost_type", nullable: false },
    { name: "contract_type", udt: "contract_type", nullable: false },
    { name: "description", udt: "text", nullable: false },
    { name: "quantity", udt: "numeric", nullable: false },
    { name: "unit_rate", udt: "numeric", nullable: false },
    { name: "markup_pct", udt: "numeric", nullable: false },
    { name: "extended_amount", udt: "numeric", nullable: true },
    { name: "similarly_situated", udt: "bool", nullable: true },
    { name: "sub_small_business_status", udt: "small_business_status", nullable: true },
    { name: "sub_subcontract_naics", udt: "varchar", nullable: true },
    ...stamps,
  ],
  vendor_quotes: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "solicitation_id", udt: "uuid", nullable: false },
    { name: "vendor_id", udt: "uuid", nullable: true },
    { name: "prospect_id", udt: "uuid", nullable: true },
    { name: "token_jti", udt: "text", nullable: true },
    { name: "status", udt: "quote_status", nullable: false },
    { name: "total_price", udt: "numeric", nullable: true },
    { name: "period_of_performance", udt: "text", nullable: true },
    { name: "pay_when_paid", udt: "bool", nullable: false },
    { name: "notes", udt: "text", nullable: true },
    { name: "ai_rank", udt: "int4", nullable: true },
    { name: "ai_rationale", udt: "text", nullable: true },
    { name: "evaluated_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  ar_followups: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "contract_id", udt: "uuid", nullable: false },
    { name: "milestone_id", udt: "uuid", nullable: true },
    { name: "amount_due", udt: "numeric", nullable: true },
    { name: "due_date", udt: "timestamptz", nullable: true },
    { name: "status", udt: "ar_followup_status", nullable: false },
    { name: "next_followup_at", udt: "timestamptz", nullable: true },
    ...stamps,
  ],
  contract_milestones: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "contract_id", udt: "uuid", nullable: false },
    { name: "sequence", udt: "int4", nullable: false },
    { name: "description", udt: "text", nullable: false },
    { name: "amount", udt: "numeric", nullable: true },
    { name: "due_date", udt: "timestamptz", nullable: true },
    { name: "status", udt: "milestone_status", nullable: false },
    ...stamps,
  ],
  contracts: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "solicitation_id", udt: "uuid", nullable: true },
    { name: "proposal_id", udt: "uuid", nullable: true },
    { name: "awarded_vendor_id", udt: "uuid", nullable: true },
    { name: "contract_type", udt: "contract_type", nullable: false },
    { name: "total_value", udt: "numeric", nullable: true },
    { name: "pop_start", udt: "timestamptz", nullable: true },
    { name: "pop_end", udt: "timestamptz", nullable: true },
    { name: "status", udt: "contract_status", nullable: false },
    { name: "esign_status", udt: "esign_status", nullable: false },
    ...stamps,
  ],
  documents: [
    { name: "id", udt: "uuid", nullable: false },
    { name: "org_id", udt: "uuid", nullable: false },
    { name: "entity_type", udt: "document_entity_type", nullable: false },
    { name: "solicitation_id", udt: "uuid", nullable: true },
    { name: "vendor_id", udt: "uuid", nullable: true },
    { name: "prospect_id", udt: "uuid", nullable: true },
    { name: "quote_id", udt: "uuid", nullable: true },
    { name: "proposal_id", udt: "uuid", nullable: true },
    { name: "contract_id", udt: "uuid", nullable: true },
    { name: "milestone_id", udt: "uuid", nullable: true },
    { name: "kind", udt: "document_kind", nullable: false },
    { name: "storage_key", udt: "text", nullable: false },
    { name: "content_type", udt: "text", nullable: false },
    { name: "byte_size", udt: "int4", nullable: false },
    { name: "sha256", udt: "varchar", nullable: true },
    { name: "magic_byte_validated", udt: "bool", nullable: false },
    ...stamps,
  ],
};

export const EXPECTED_TABLES: string[] = Object.keys(EXPECTED_COLUMNS);

/** All 25 enums and their labels, in sort order. */
export const EXPECTED_ENUMS: Record<string, string[]> = {
  actor_type: ["SYSTEM", "ADMIN", "VENDOR", "TOKEN"],
  ar_followup_status: ["SCHEDULED", "SENT", "PAID", "ESCALATED", "WRITTEN_OFF"],
  award_amount_kind: ["EXACT", "ESTIMATED", "CEILING", "OBLIGATED", "UNKNOWN"],
  classification_source: ["AI_TRIAGE", "HUMAN", "SAM_GOV", "HEURISTIC"],
  contract_status: ["PENDING_SIGNATURE", "ACTIVE", "COMPLETED", "TERMINATED", "CLOSED_OUT"],
  contract_type: ["FFP", "TM", "FFP_MILESTONE"],
  cost_type: ["LABOR", "MATERIAL", "ODC", "SUBCONTRACT", "TRAVEL"],
  document_entity_type: [
    "SOLICITATION",
    "VENDOR",
    "VENDOR_PROSPECT",
    "VENDOR_QUOTE",
    "PROPOSAL",
    "CONTRACT",
    "CONTRACT_MILESTONE",
  ],
  document_kind: [
    "SOLICITATION_ATTACHMENT",
    "CAPABILITY_STATEMENT",
    "COI",
    "W9",
    "QUOTE",
    "PROPOSAL_DRAFT",
    "PROPOSAL_FINAL",
    "SIGNED_CONTRACT",
    "DELIVERABLE",
    "OTHER",
  ],
  esign_status: ["NOT_STARTED", "SENT", "SIGNED", "DECLINED", "EXPIRED"],
  milestone_status: ["PENDING", "IN_PROGRESS", "COMPLETED", "INVOICED", "PAID"],
  notice_type: [
    "SOLICITATION",
    "COMBINED_SYNOPSIS_SOLICITATION",
    "PRESOLICITATION",
    "SOURCES_SOUGHT",
    "RFI",
    "SPECIAL_NOTICE",
    "AWARD_NOTICE",
    "JUSTIFICATION",
  ],
  outreach_status: [
    "DRAFT",
    "PENDING_APPROVAL",
    "APPROVED",
    "SENT",
    "BOUNCED",
    "RESPONDED",
    "OPTED_OUT",
    "CANCELLED",
  ],
  outreach_step: ["DAY_0", "DAY_3", "DAY_7"],
  proposal_status: [
    "DRAFT",
    "PRICING_REVIEW",
    "COMPLIANCE_REVIEW",
    "COUNSEL_REVIEW",
    "READY_TO_SUBMIT",
    "SUBMITTED",
    "WON",
    "LOST",
    "WITHDRAWN",
  ],
  prospect_source: ["DISCOVERY", "TOKENIZED_SUBMISSION", "MANUAL", "REFERRAL"],
  prospect_status: [
    "NEW",
    "SCREENED",
    "CONTACTED",
    "RESPONDED",
    "QUALIFIED",
    "PROMOTED",
    "DECLINED",
    "OPTED_OUT",
  ],
  quote_status: [
    "INVITED",
    "DRAFT",
    "SUBMITTED",
    "UNDER_REVIEW",
    "SHORTLISTED",
    "REJECTED",
    "WITHDRAWN",
    "SELECTED",
  ],
  set_aside_type: ["NONE", "TOTAL_SMALL_BUSINESS", "EIGHT_A", "HUBZONE", "SDVOSB", "WOSB", "OTHER"],
  small_business_status: ["SMALL", "OTHER_THAN_SMALL", "UNKNOWN"],
  solicitation_status: [
    "PENDING_TRIAGE",
    "TRIAGE_COMPLETE",
    "NO_GO",
    "READY_FOR_SOURCING",
    "AWAITING_APPROVAL",
    "SOURCING_IN_PROGRESS",
    "PRICING_PENDING",
    "PROPOSAL_DRAFT",
    "SUBMITTED",
    "AWARDED",
    "CLOSED",
    "REJECTED",
  ],
  token_purpose: ["QUOTE_SUBMISSION", "OPT_OUT"],
  user_role: ["ADMIN", "VENDOR"],
  vendor_status: ["PENDING_REVIEW", "VETTED", "NON_COMPLIANT", "EXCLUDED"],
  zero_float_fit: ["STRONG", "MODERATE", "WEAK", "NONE"],
};
